name: build-push-ecr

on:
  workflow_call:
    inputs:
      aws_region:
        type: string
        required: true
      dockerfile:
        type: string
        required: false
        default: Dockerfile
      ecr_repository_name:
        type: string
        required: true
      docker_tag:
        type: string
        required: true
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true

jobs:

  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ inputs.aws_region }}
      - name: Login to Amazon ECR
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@v1
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build the Docker image and push to ECR
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ${{ inputs.dockerfile }}
          tags: ${{ steps.login_ecr.outputs.registry }}/${{ inputs.ecr_repository_name }}:${{ inputs.docker_tag }}
          cache-from: type=gha,scope=${{ inputs.docker_tag }}--${{ inputs.ecr_repository_name }}
          cache-to: type=gha,mode=max,scope=${{ inputs.docker_tag }}--${{ inputs.ecr_repository_name }}
