name: review-app
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_call:
    inputs:
      aws_region:
        type: string
        required: true
      docker_tag:
        type: string
        required: true
      ecr_repository_name:
        type: string
        required: false
      ecs_cluster_name:
        type: string
        required: true
      ecs_service_name:
        type: string
        required: true
      extra_environment_variables:
        type: string
        required: false
      images:
        type: string
        required: false
      qa_env_name:
        type: string
        required: true
      tf_directory:
        type: string
        required: true
      tf_version:
        type: string
        default: 1.6.0
      tfstate_s3_bucket:
        type: string
        required: true
      docker_build_args:
        type: string
        required: false
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      tfc_token:
        required: true
      docker_build_args:
        required: false
    outputs:
      review_app_url:
        description: The URL of the review app
        value: ${{ jobs.create_update.outputs.review_app_url }}

jobs:
  read_images_to_build:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.parse.outputs.images }}
    env:
      images: ${{ inputs.images }}  # Default value
    steps:
      - name: Parse images to JSON
        id: parse
        run: |
          echo ::group::Read images to build from legacy ecr_repository_name parameter
          echo "${{ inputs.images }}" >> images  # Default, new value
          if [[ -n "${{ inputs.ecr_repository_name }}" ]]; then
            echo "${{ inputs.ecr_repository_name }}: ./Dockerfile" >> images
          fi
          echo ::endgroup::

          images_json=$(cat images | jq -Rnc '[[inputs][] | capture("^(?<ecr_repository_name>[^:]+):\\s*(?<dockerfile>[^$]*)$")]')
          echo "images=${images_json}" >> $GITHUB_OUTPUT
          jq <<< ${images_json}  # Debug
  build_push:  # Build the Docker image
    runs-on: ubuntu-latest
    needs: read_images_to_build
    strategy:
      matrix:
        image: ${{ fromJSON(needs.read_images_to_build.outputs.images) }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ inputs.aws_region }}
      - name: Login to Amazon ECR
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Fetch the source code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Normalize build args
        id: build_args
        shell: python
        run: |
          import os
          input_build_args = '''${{ inputs.docker_build_args }}'''.strip()
          secret_build_args = '''${{ secrets.docker_build_args }}'''.strip()
          result = '\n'.join(filter(None, [input_build_args, secret_build_args]))
          with open(os.environ['GITHUB_OUTPUT'], 'a') as output:
            print('BUILD_ARGS<<EOF', file=output)
            print(result, file=output)
            print('EOF', file=output)
      - name: Build and push the Docker image to AWS ECR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ${{ matrix.image.dockerfile }}
          tags: ${{ steps.login_ecr.outputs.registry }}/${{ matrix.image.ecr_repository_name }}:${{ inputs.docker_tag }}
          build-args: ${{ steps.build_args.outputs.BUILD_ARGS }}
          cache-from: type=gha,scope=${{ github.event.repository.default_branch }}--${{ matrix.image.ecr_repository_name }}
          cache-to: type=gha,mode=max,scope=${{ inputs.docker_tag }}
  create_update:
    needs: build_push
    runs-on: ubuntu-latest
    env:
      ENV_EXISTS: 0  # May be overriden later on
      TF_BUCKET: ${{ inputs.tfstate_s3_bucket }}
      TF_STATE: ${{ github.repository }}/${{ inputs.docker_tag }}.tfstate
    outputs:
      review_app_url: ${{ steps.output_review_app_url.outputs.review_app_url }}
    steps:
      - name: Fetch the source code
        uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.tf_version }}
          cli_config_credentials_token: ${{ secrets.tfc_token }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ inputs.aws_region }}
      - name: Check if ECS service already exists
        run: |
          services=$(aws ecs list-services --cluster ${{ inputs.ecs_cluster_name }})
          echo "ENV_EXISTS=$(echo $services | grep ${{ inputs.ecs_service_name }} | wc -l)" >> $GITHUB_ENV
      - name: Set extra environment variables
        if: inputs.extra_environment_variables
        run: echo "${{ inputs.extra_environment_variables }}" >> $GITHUB_ENV
      - name: Initialize Terraform workspace
        run: terraform init -backend-config="bucket=${{ env.TF_BUCKET }}" -backend-config="key=${{env.TF_STATE}}"
        working-directory: ${{ inputs.tf_directory }}
      - name: Apply Terraform configuration
        run: terraform apply -auto-approve
        env:
          TF_VAR_qa_env_name: ${{ inputs.qa_env_name }}
          # NOTE: Other variables may be included by extra_environment_variables
        working-directory: ${{ inputs.tf_directory }}
      - name: Restart ECS service (if already existed)
        if: env.ENV_EXISTS == 1
        run: aws ecs update-service --cluster ${{ inputs.ecs_cluster_name }} --service ${{ inputs.ecs_service_name }} --force-new-deployment
      - name: Wait for ECS service to be stable
        run: aws ecs wait services-stable --cluster ${{ inputs.ecs_cluster_name }} --services ${{ inputs.ecs_service_name }}
      - name: Output the review app URL
        id: output_review_app_url
        run: |
          url=$(terraform output -raw review_app_url)
          echo "review_app_url=${url}" >> $GITHUB_OUTPUT
        working-directory: ${{ inputs.tf_directory }}
